In [1]:
from main import init_config
from controller import Controller
from dataset.process import TokenParser

import numpy as np

2021-12-19 00:04:35.677537: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
ctrl = Controller(*init_config())

Running the DreamProlog algorithm.
There was a problem with the provided arguments. The program will run in the default setting:
--configs prolog --logdir logdir
Namespace(act='elu', action_gnn_hidden_act=64, action_gnn_hidden_val=200, action_gnn_layers=6, action_gnn_next_shape=(32, 64, 32), action_gnn_start_shape=(4, 1, 4), action_repeat=1, actor_disc=5, actor_dist='normal', actor_entropy='1e-4', actor_grad_clip=100, actor_init_std=1.0, actor_layers=4, actor_lr=0.001, actor_min_std=0.1, actor_outscale=0.0, actor_state_entropy=0.0, actor_temp=0.1, atari_grayscale=False, behavior_stop_grad=True, clip_rewards='identity', collect_dyn_sample=True, dataset_size=100000, debug=False, disag_layers=1, disag_log=True, disag_models=3, disag_offset=0, disag_target='embed', disag_units=200, discount=0.95, discount_lambda=0.8, discount_layers=2, discount_scale=1.0, dyn_cell='gru', dyn_deter=512, dyn_discrete=32, dyn_hidden=512, dyn_input_layers=5, dyn_mean_act='none', dyn_min_std=0.1, dyn_output_lay

usage: ipykernel_launcher.py [-h] --configs CONFIGS [CONFIGS ...] --logdir
                             LOGDIR
ipykernel_launcher.py: error: the following arguments are required: --configs, --logdir
2021-12-19 00:04:37.114704: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-19 00:04:37.115382: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-12-19 00:04:37.146240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:05:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemoryBandwidth: 607.97GiB/s
2021-12-19 00:04:37.147162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:09:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemor

Suite: prolog
Found 131 problem files.
Query:
    init_python("leancop/theorems/m2n140/t48_funct_2.p",[conj, nodef, eager_reduction(1)],GnnInput, SimpleFeatures, TextFeatures, TextActions, ActionsMask, Result) 

Suite: prolog
Found 131 problem files.
Query:
    init_python("leancop/theorems/m2n140/t106_relat_1.p",[conj, nodef, eager_reduction(1)],GnnInput, SimpleFeatures, TextFeatures, TextActions, ActionsMask, Result) 

Prefill dataset (0 steps).
Loaded problem: m2n140__t55_tops_1
Found 131 problem files.
Query:
    init_python("leancop/theorems/m2n140/t25_ordinal1.p",[conj, nodef, eager_reduction(1)],GnnInput, SimpleFeatures, TextFeatures, TextActions, ActionsMask, Result) 

Eval episode has 6 steps and return -1.000.
[40007] eval_return -1.0 / eval_length 6.0 / eval_episodes 7.0


/home/kristsz/DreamProLog/envs/wrappers.py:57: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  value = np.array(value)


In [3]:
meta = ctrl.datasetManager._train_eps._meta

In [15]:
ds = []
for v in meta.values():
    ds.extend([str(s)[1:] for s in v['action_space_text']])
    
parser = TokenParser()

def pad(narr):
    size = narr.size
    return np.pad(narr, [0, 128-size])

parsed_ds = []
for dp in ds:
    parsed_ds.append(pad(np.array(parser.parse(dp), dtype = np.int32)))

In [16]:
for i in range(6):
    print(ds[i], parsed_ds[i], sep='\n', end='\n\n')

# EOP NEG r1_tarski 2 skolem_3 0 skolem_5 0 EOP
[2 3 4 5 6 7 8 9 8 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

NEG r1_tarski 2 skolem_3 0 skolem_5 0 EOP # EOP
[4 5 6 7 8 9 8 3 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

# EOP NEG = 2 skolem_4 0 k6_subset_1 2 skolem_5 0 skolem_3 0 EOP
[ 2  3  4 10  6 11  8 12  6  9  8  7  8  3  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  

In [17]:
import tensorflow as tf
BATCH_SIZE = 32
def generator():
    while True:
        x = tf.constant([parsed_ds[np.random.randint(len(parsed_ds))] for i in range(BATCH_SIZE)])
        yield x, x

In [18]:
next(iter(generator()))

(<tf.Tensor: shape=(32, 128), dtype=int32, numpy=
 array([[  4,  10,   6, ...,   0,   0,   0],
        [ 10,   6,  13, ...,   0,   0,   0],
        [ 22,   6,  13, ...,   0,   0,   0],
        ...,
        [ 28,  24,  13, ...,   0,   0,   0],
        [119,   6,  13, ...,   0,   0,   0],
        [ 73,  24,  13, ...,   0,   0,   0]], dtype=int32)>,
 <tf.Tensor: shape=(32, 128), dtype=int32, numpy=
 array([[  4,  10,   6, ...,   0,   0,   0],
        [ 10,   6,  13, ...,   0,   0,   0],
        [ 22,   6,  13, ...,   0,   0,   0],
        ...,
        [ 28,  24,  13, ...,   0,   0,   0],
        [119,   6,  13, ...,   0,   0,   0],
        [ 73,  24,  13, ...,   0,   0,   0]], dtype=int32)>)

In [19]:
sgn = tf.TensorSpec((BATCH_SIZE, 128), dtype=tf.int32)
tf_ds = tf.data.Dataset.from_generator(generator, output_signature = (sgn, sgn))

In [20]:
m=0
for p in parsed_ds:
    m = max(m, len(p))
print(m, len(ds))

128 11961


In [21]:
del parser

In [22]:
ds_it = iter(tf_ds)
next(ds_it)

(<tf.Tensor: shape=(32, 128), dtype=int32, numpy=
 array([[ 10,   6,  13, ...,   0,   0,   0],
        [ 15,   6,  13, ...,   0,   0,   0],
        [  4, 102,   6, ...,   0,   0,   0],
        ...,
        [ 15,   6,  58, ...,   0,   0,   0],
        [  4,  10,   6, ...,   0,   0,   0],
        [ 29,  24,  13, ...,   0,   0,   0]], dtype=int32)>,
 <tf.Tensor: shape=(32, 128), dtype=int32, numpy=
 array([[ 10,   6,  13, ...,   0,   0,   0],
        [ 15,   6,  13, ...,   0,   0,   0],
        [  4, 102,   6, ...,   0,   0,   0],
        ...,
        [ 15,   6,  58, ...,   0,   0,   0],
        [  4,  10,   6, ...,   0,   0,   0],
        [ 29,  24,  13, ...,   0,   0,   0]], dtype=int32)>)

In [23]:
from transformer import EncoderLayer, DecoderLayer, MultiHeadAttention
class Encoder(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff, querry,rate):
        super().__init__()
        self.layers = [EncoderLayer(d_model, num_heads, dff, rate) for i in range(5)]
        
        self.mha = MultiHeadAttention(d_model, num_heads)
        
        shape=(BATCH_SIZE, querry, d_model)
        self.variable = tf.Variable(tf.random.uniform(
            shape, minval=0, maxval=1, dtype=tf.dtypes.float32, seed=69, name=None))
                                    
        
    def call(self, x, training):
        for layer in self.layers:
            x = layer(x,training, None)
            
        x, _ = self.mha(x,x, self.variable, None)
        
        return x
    
class Decoder(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff, output_length, rate):
        super().__init__()
        self.layers = [DecoderLayer(d_model, num_heads, dff, rate) for i in range(5)]
        
        shape=(BATCH_SIZE, output_length, d_model)
        self.variable = tf.Variable(tf.random.uniform(
            shape, minval=0, maxval=1, dtype=tf.dtypes.float32, seed=69, name=None))
        
        
    def call(self, x, training):
        y = self.variable
        for layer in self.layers:
            y, _, _ = layer(y, x, training, None, None)
            
        return y
        
class Net(tf.keras.Model):
    def __init__(self, d_model, num_heads, dff):
        super().__init__()
        self.encoder = Encoder(d_model, num_heads, dff, 4, 0.04)  
        self.enc_embed = tf.keras.layers.Embedding(300, d_model)
        self.decoder = Decoder(d_model, num_heads, dff, 128, 0.04)
        
        self.dropout = tf.keras.layers.Dropout(0.08)
        
        self.dense = tf.keras.layers.Dense(300, activation='relu', use_bias=False)
        
    def call(self, x, training):
        x = self.enc_embed(x)
        x = self.encoder(x, training)
        x = self.dropout(x)
        x = self.decoder(x, training)
        
        x = self.dense(x)
        
        return x

In [24]:
model = Net(96, 6, 192)
x, y_true = next(ds_it)
y_pred = model(x, False)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss(y_true, y_pred))
model.compile(optimizer="Adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=[])

2021-12-19 00:08:20.164942: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10


tf.Tensor(6.0104895, shape=(), dtype=float32)


In [ ]:
model.fit(tf_ds, epochs = 1)

  10335/Unknown - 334s 32ms/step - loss: 0.8715

In [93]:

x, y_true = next(ds_it)
y_pred = model(x, False)
y_pred = tf.nn.softmax(y_pred, axis=-1)
y_pred = tf.math.argmax(y_pred, axis=-1)
print(x[:4], y_pred[:4], sep='\n\n')

Error in callback <function _WandbInit._resume_backend at 0x7f8d7af95d40> (for pre_run_cell):


Exception: The wandb backend process has shutdown

tf.Tensor(
[[  2   3   4  22   6   9   8  39  24  20   8   3   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [ 22   6  13  39  24  14   3  38  24  14   3  46  24  14   3  37  24  14
    3   4  34  24  14   3  22   6  17  39  24  14   3  22   6  19  39  24
   14   3   4  10   6  19  49  21  14  13  17   3  48  21  14  19  13   3
   48  21  14  19  17   3   4  48  21  14  16  33  19  17  13  14  17   3
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   

Exception: The wandb backend process has shutdown

In [89]:
tf.Tensor(
[[ 10   6  13  14   3   4 119   6  17  14   3 119   6  19  13   3  10   6
   19  17   3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  4  22   6  13  14   3  22   6  17  19   3  10   6  17  13   3  10   6
   19  14   3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  2   3   4 125  24  16   8   3   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  4  34  24  13   3  38  24  13   3  46  24  13   3  37  24  13   3  22
    6  14  39  24  13   3  22   6  17  39  24  13   3  22   6  19  39  24
   13   3   4  10   6  19  49  21  13  14  17   3  48  21  13  19  14   3
   48  21  13  19  17   3   4  48  21  13  16  33  19  17  14  13  14   3
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]], shape=(4, 128), dtype=int32)

tf.Tensor(
[[10  6 13 14  3  4  6  6 17 19  3 10  6 13 13  3 10  6 19 17  3  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [10  6 13 14  3  4 22  6 17 19  3 10  6 13 13  3 10  6 19 17  3  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [ 4  3  4 20 24  3  8  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]
 [38 24 13  3 38 24 13  3 37 24 13  3  3 34 24 13  3 22 34 24 13 24 13  3
  22  6  6 39 13 13  3 22  6 19 39 24 13 13 10 10  6 19 49 49  3  3  3  3
  48 21 14 19 14 13 48 21 13 13 13 21 48 48 21 16 16 13 21 19  3 14  3  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0]], shape=(4, 128), dtype=int64)

Error in callback <function _WandbInit._resume_backend at 0x7f8d7af95d40> (for pre_run_cell):


Exception: The wandb backend process has shutdown

5

Error in callback <function _WandbInit._pause_backend at 0x7f8d707a2830> (for post_run_cell):


Exception: The wandb backend process has shutdown